---
- name: Deploy WordPress on VPS
  hosts: wordpress_servers
  become: yes
  gather_facts: yes
  
  vars:
    ansible_ssh_pipelining: yes
    
  pre_tasks:
    - name: Wait for SSH connection
      wait_for_connection:
        timeout: 300
        
    - name: Gather facts
      setup:
      
  roles:
    - docker
    - nginx
    - app

    
    